Add fail on logs generated

diff --git a/.github/workflows/gh-workflow-auditor.yaml b/.github/workflows/gh-workflow-auditor.yaml
--- a/.github/workflows/gh-workflow-auditor.yaml
+++ b/.github/workflows/gh-workflow-auditor.yaml
@@ -29,3 +29,11 @@ jobs:
         run: |
           ghwfauditor --type user enzowritescode --log-level $LOG_LEVEL
 
+          # Check if the log file has any content
+          if [ -s scan.log ]; then
+            echo "Issues were found! Failing the workflow."
+            exit 1
+          else
+            echo "No findings. Success"
+          fi
+
